### ISSUE TITLE
Not working for player without mojang cape.

### ISSUE THREAD

**Issue by kakis69** [SuchBlue/of-capes#1]
If a player does not have an official Mojang cape, no capes will be loaded for that player. Capes for players with official Mojang capes are displayed.

**Comment by SuchBlue** [comment]
I'm unable to reproduce this. Even after using an offline name of someone that doesn't have a Mojang cape but has an OptiFine cape, I can still see the OptiFine cape. If you can provide me with more information that might help me solve your issue, that would be appreciated

**Comment by kakis69** [comment]
> I'm unable to reproduce this. Even after using an offline name of someone that doesn't have a Mojang cape but has an OptiFine cape, I can still see the OptiFine cape. If you can provide me with more information that might help me solve your issue, that would be appreciated

I don't have a Mojang cape or an Optifine cape. Now I wanted to try out the code and added it to my mod and switched the server that provides the capes to one of mine. Now I can't give myself a cape, but other players who have a Mojang cape can.
